spring.datasource.url=jdbc:postgresql://${DB_ENDPOINT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

management.metrics.enable.jvm=true

management.metrics.export.cloudwatch.enabled=true
management.metrics.export.cloudwatch.namespace=todo-application

logging.level.com.amazonaws.util.EC2MetadataUtils=error
cloud.aws.stack.auto=false

cloud.aws.region.auto=true
cloud.aws.region.use-default-aws-region-chain=true
cloud.aws.credentials.use-default-aws-credentials-chain=true