#!/usr/bin/env bash

set -eu

DIR="$( cd "$(dirname "$0")" ; pwd -P )"
DOCKER_IMAGE_NAME="todo-backend-spring-boot-jooq"

task_usage() {
  echo "usage: $0 clean | build | test"
  exit 1
}

task_build() {
  "${DIR}/gradlew" clean assemble
  (
    cd "${DIR}"
    docker build -t "${DOCKER_IMAGE_NAME}" .
  )
}

task_generate() {
  "${DIR}/gradlew" clean build generateOpenApiDocs
}

task_test() {
  "${DIR}/gradlew" check
}

task_clean() {
  "${DIR}/gradlew" clean
}

cmd="${1:-}"
shift || true
case "$cmd" in
  clean) task_test ;;
  generate) task_generate ;;
  build) task_build ;;
  test) task_test ;;
  *) task_usage ;;
esac
