#!/usr/bin/env bash

set -eu

DIR="$( cd "$(dirname "$0")" ; pwd -P )"
DOCKER_IMAGE_NAME="todo-frontend-angular"

task_usage() {
  echo "usage: $0 clean | build | test"
  exit 1
}

task_build() {
  ng build --prod
  (
    cd "${DIR}"
    docker build -t "${DOCKER_IMAGE_NAME}" .
  )
}

task_generate() {
  ng-openapi-gen --input "${DIR}/../todo-backend-spring-boot-jooq/build/todo-api.json" --output "${DIR}/src/generated/"
}

task_test() {
  echo "test"
}

task_clean() {
  echo "clean"
}

cmd="${1:-}"
shift || true
case "$cmd" in
  clean) task_test ;;
  generate) task_generate ;;
  build) task_build ;;
  test) task_test ;;
  *) task_usage ;;
esac
