management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,metrics,beans

springdoc:
  api-docs:
    enabled: true
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'
    configUrl: '/api-docs/swagger-config'
    urls:
      - name: ToDo API
        url: '/api-docs'