#!/usr/bin/env bash

set -eu

DIR="$( cd "$(dirname "$0")" ; pwd -P )"
DOCKER_IMAGE_NAME="todo-backend-spring-boot-jooq"

source "${DIR}/../ctuhl/lib/shell/log.sh"

function task_usage {
  echo "Usage: $0 clean | generate | build | test"
  exit 1
}

task_clean() {
  "${DIR}/gradlew" clean
}

function task_generate {
  # snippet:gradle_jooq_run
  "${DIR}/gradlew" generateJooq
  # /snippet:gradle_jooq_run
}

task_build() {
  "${DIR}/gradlew" clean assemble
  #(
    #cd "${DIR}"
    #docker build -t "${DOCKER_IMAGE_NAME}" .
  #)
}

task_test() {
  "${DIR}/gradlew" check
}

arg=${1:-}
shift || true
case ${arg} in
  clean) task_clean "$@" ;;
  generate) task_generate "$@" ;;
  build) task_build "$@" ;;
  test) task_test "test" "$@" ;;
  *) task_usage ;;
esac
