#!/usr/bin/env bash

set -eu

DIR="$( cd "$(dirname "$0")" ; pwd -P )"

task_usage() {
  echo "usage: $0 clean | build | test"
  exit 1
}

task_build() {
  "${DIR}/gradlew" build
}

task_generate() {
  "${DIR}/gradlew" clean ktlintFormat build generateOpenApiDocs
}

task_test() {
  "${DIR}/gradlew" check
}

task_clean() {
  "${DIR}/gradlew" clean
}

cmd="${1:-}"
shift || true
case "$cmd" in
  clean) task_test ;;
  generate) task_generate ;;
  build) task_build ;;
  test) task_test ;;
  *) task_usage ;;
esac
