version: "3"
services:
  todo-db:
    image: postgres
    environment:
      - POSTGRES_DB=todo-database
      - POSTGRES_USER=todo-application
      - POSTGRES_PASSWORD=724e0c7b-d542-4b79-b17a-e597be5e8ceb

  todo-backend:
    image: todo-backend-spring-boot-jooq
    environment:
      - DB_ENDPOINT=todo-db
      - DB_NAME=todo-database
      - DB_USER=todo-application
      - DB_PASSWORD=724e0c7b-d542-4b79-b17a-e597be5e8ceb
    ports:
      - 9080:8080
    links:
      - todo-db

  todo-frontend:
    image: todo-frontend-angular
    ports:
      - 7080:8080

  todo-ingress:
    image: todo-ingress
    ports:
      - 8080:80
    links:
      - todo-backend
      - todo-frontend
